Module6 task2
htmlacademy-php/1833643-yeticave-12 pull request #11
Opened 2021-12-17 22:55 UTC by grinevie

Получение данных из форм

2021-12-17 22:55 UTC, grinevie commented
Получение данных из форм

2021-12-20 10:48 UTC, mihan007 requested changes
Надо немного доделать

2021-12-20 10:48 UTC, mihan007 commented on add-lot.php
> +                <span class="form__error"><?= isset($errors["category"]) ? $errors["category"] : ""?></span>
лучше через `??`

2021-12-20 10:48 UTC, mihan007 commented on add.php
> +        if (false === is_date_valid($lot_date)) {
в теле if не надо сравнивать с true/false, сам оператор это сделает автоматически. то есть тут будет `!is_date_valid`

2021-12-20 10:48 UTC, mihan007 commented on add.php
> +    if (null !== $name) {
очень длинный класс, надо разбить на функции, где функция каждая проверяет свое поле. вынести эти функции в отдельный файл и тут уже ими пользоваться

2021-12-20 10:48 UTC, mihan007 commented on add.php
> +
достаточно одной пустой строки

2021-12-28 04:03 UTC, mihan007 approved these changes
Поправить мелочи в следующем PR

2021-12-28 04:03 UTC, mihan007 commented on add.php
> +//    if (null !== $lot_date) {
Убираем мертвый код

2021-12-28 04:03 UTC, mihan007 commented on check_err.php
> +if (isset($_POST[$key]) && $_POST[$key]) {
что-то с отступами

2021-12-28 04:03 UTC, merged