Шаблонизация проекта
htmlacademy-php/1833643-yeticave-12 pull request #5
Opened 2021-08-12 23:36 UTC by grinevie

2021-08-13 04:38 UTC, mihan007 requested changes
Приятно видеть очень сильную работу! Посмотри мои предложения по улучшению, пожалуйста

2021-08-13 04:38 UTC, mihan007 commented on index.php
> +    return $result;
1. кстати, можно сделать сразу `return "{$amount} ₽"`
2. визуально симпатичнее, если return отделен от кода функции пустой строкой

2021-08-13 04:38 UTC, mihan007 commented on index.php
> +$page_content = include_template('main.php', $data = ['categories' => $categories, 'units' => $units]);
1. Нет необходимости в вспомогательной переменной $data
2. Посмотри функцию compact - сильно упростит передачу параметров внутрь шаблонов

2021-08-13 04:38 UTC, mihan007 commented on templates/layout.php
> +    <title><?= $page_name ?></title>
тут все же title. попробуем изменить имя переменной?

2021-08-13 04:38 UTC, mihan007 commented on templates/layout.php
> +        <?= $page_content; ?>
все правильно сделал👍

2021-08-13 04:38 UTC, mihan007 commented on templates/main.php
> +                    <h3 class="lot__title"><a class="text-link" href="pages/lot.html"><?= htmlspecialchars(
для простоты я рекомендую экранирование вывода вынести в функцию с коротким именем. внутри нее также будет `return htmlspecialchars($string);`, но назвать ее можно проще и меньше по клавишам нажимать. например, `function e($string)`

2021-08-14 04:42 UTC, mihan007 approved these changes
Bellissimo! 

Есть небольшое замечание по форматированию, поправь в следующем задании, пожалуйста.

2021-08-14 04:42 UTC, mihan007 commented on index.php
> +    }
скобка где-то не туда пристроилась, есть напонятный отступ. есть подозрение, что форматтер PSR-12 не запускается перед коммитом. Ниже показываю галочку, чтобы оно само делалось
![2021-08-14 at 07 37](https://user-images.githubusercontent.com/939122/129434139-b46550e4-c9fa-4726-9dc4-bcc20effa46e.png)

2021-08-14 04:42 UTC, mihan007 commented on index.php
> +     * return number_format(ceil($amount),0, '.',' ').' ₽';
Упоремся и сделаем))) `return ($amount >= 1000) ? number_format(ceil($amount),0, '.',' ').' ₽' : $amount`

Но нет, пусть лучше будет больше строк, но понятнее

2021-08-14 04:42 UTC, mihan007 commented on templates/main.php
> +                                $unit['name']
может я ошибаюсь, но выглядит так будто функцию разорвало на 2 строки. сейчас допускается использовать в одной строке 120 символов и не делать переноса. Раньше рекомендовалось 80 из-за маленьких мониторов. Посмотри в настройках шторма - может он до сих пор в прошлом веке и насильно перенос делает на 80м символе

2021-08-14 04:43 UTC, merged

2021-08-14 22:27 UTC, grinevie commented on index.php
> +    }
> скобка где-то не туда пристроилась, есть напонятный отступ. есть подозрение, что форматтер PSR-12 не запускается перед коммитом. Ниже показываю галочку, чтобы оно само делалось
> ![2021-08-14 at 07 37](https://user-images.githubusercontent.com/939122/129434139-b46550e4-c9fa-4726-9dc4-bcc20effa46e.png)

А что не так, посмотрел мануал PSR12. Там if так форматируется, отступ блока четыре пробела.

2021-08-14 22:34 UTC, grinevie commented on templates/main.php
> +                                $unit['name']
В настройках 120 стоит. Собрал функцию в целое, реформат не рвет ее, что с ней было, непонятно.